apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: my-nginx
  namespace: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: my-nginx
